<?php
/**
 * @file
 * bebinh_content.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function bebinh_content_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "flexslider" && $api == "flexslider_default_preset") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function bebinh_content_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function bebinh_content_node_info() {
  $items = array(
    'page' => array(
      'name' => t('Basic page'),
      'base' => 'node_content',
      'description' => t('Use <em>basic pages</em> for your static content, such as an \'About us\' page.'),
      'has_title' => '1',
      'title_label' => t('Tiêu đề'),
      'help' => '',
    ),
    'slideshow' => array(
      'name' => t('Slideshow'),
      'base' => 'node_content',
      'description' => t('Use to make slideshow'),
      'has_title' => '1',
      'title_label' => t('Tiêu đề'),
      'help' => '',
    ),
  );
  return $items;
}
